// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwitchFully.IntakeApp.Data;

namespace SwitchFully.IntakeApp.Data.Migrations
{
    [DbContext(typeof(SwitchFullyIntakeAppContext))]
    [Migration("20181210101444_candidate")]
    partial class candidate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SwitchFully.IntakeApp.Domain.Candidates.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("SwitchFully.IntakeApp.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<DateTime?>("LastLogon");

                    b.Property<string>("LastName");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SwitchFully.IntakeApp.Domain.Candidates.Candidate", b =>
                {
                    b.OwnsOne("System.Net.Mail.MailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("CandidateId");

                            b1.Property<string>("Address")
                                .HasColumnName("Email");

                            b1.ToTable("Candidates");

                            b1.HasOne("SwitchFully.IntakeApp.Domain.Candidates.Candidate")
                                .WithOne("Email")
                                .HasForeignKey("System.Net.Mail.MailAddress", "CandidateId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("SwitchFully.IntakeApp.Domain.Users.User", b =>
                {
                    b.OwnsOne("SwitchFully.IntakeApp.Domain.Users.UserSecurity", "SecurePassword", b1 =>
                        {
                            b1.Property<Guid?>("UserId");

                            b1.Property<string>("PasswordHash")
                                .HasColumnName("PassWord");

                            b1.Property<string>("Salt")
                                .HasColumnName("SecPass");

                            b1.ToTable("Users");

                            b1.HasOne("SwitchFully.IntakeApp.Domain.Users.User")
                                .WithOne("SecurePassword")
                                .HasForeignKey("SwitchFully.IntakeApp.Domain.Users.UserSecurity", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("System.Net.Mail.MailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<string>("Address")
                                .HasColumnName("Email");

                            b1.ToTable("Users");

                            b1.HasOne("SwitchFully.IntakeApp.Domain.Users.User")
                                .WithOne("Email")
                                .HasForeignKey("System.Net.Mail.MailAddress", "UserId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
